apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: azni-project
  namespace: argocd
spec:
  description: Azni project for Helm and Kustomize integration
  sourceRepos:
    - "*"
  destinations:
    - namespace: development
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
