apiVersion: v1
kind: Service
metadata:
  name: azni-mysql-service
  namespace: azni-mysql
spec:
  selector:
    app: azni-mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30307
  type: NodePort
