apiVersion: v1
kind: Pod
metadata:
  name: azni-app-pod
  namespace: azni-namspace
  labels:
    app: azni-app
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-content
      mountPath: /usr/share/nginx/html/
      readOnly: true
  volumes:
  - name: html-content
    configMap:
      name: azni-app-html
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
