# Custom values for azni-app deployment in azni-namspace
replicaCount: 3

image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "latest"

# Command for busybox container
command:
  - "/bin/sh"
  - "-c"
  - "while true; do echo Hello from azni-app; sleep 10; done"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: azni-namespace-sctp-sandbox.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

# Add namespace-specific labels
podLabels:
  environment: production
  namespace: azni-namspace

# Add tolerations for CriticalAddonsOnly nodes
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"

# Custom probes for busybox
livenessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "exit 0"
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "exit 0"
  initialDelaySeconds: 5
  periodSeconds: 10
