# Development upgrade values
global:
  environment: development

replicaCount: 2  # Increased from 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.21"  # Upgraded from latest

# Disable MySQL to avoid PVC issues
mysql: {}

frontend:
  enabled: true
  replicaCount: 2  # Increased from 1
  
  image:
    repository: nginx
    tag: "1.21"
    pullPolicy: IfNotPresent
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: azni-app-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 150m    # Increased from 100m
    memory: 192Mi # Increased from 128Mi
  requests:
    cpu: 75m     # Increased from 50m
    memory: 96Mi  # Increased from 64Mi

autoscaling:
  enabled: true  # Enabled
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75

networkPolicy:
  enabled: false

validationHooks:
  enabled: false

nodeSelector:
  kubernetes.io/os: linux

tolerations: []
affinity: {}
