# Development environment values for azni-app
# This file contains development-specific configurations

global:
  environment: development

# Reduced replica count for development
replicaCount: 1

# Development image settings
image:
  repository: nginx
  pullPolicy: Always
  tag: "latest"

# MySQL configuration for development
mysql:
  rootPassword: "dev-root-password"
  database: "azni_dev_db"
  user: "azni_dev_user"
  password: "dev-password"
  
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3306
  
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 5Gi
    accessMode: ReadWriteOnce

# Frontend configuration for development
frontend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: nginx
    tag: "latest"
    pullPolicy: Always
  
  service:
    type: NodePort
    port: 80
    targetPort: 80

# Service configuration
service:
  type: NodePort
  port: 80

# Ingress configuration for development
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: azni-app-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits for development (lower limits)
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Autoscaling disabled for development
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

# Network policy disabled for development
networkPolicy:
  enabled: false

# Validation hooks disabled for development
validationHooks:
  enabled: false

# Development-specific node selector
nodeSelector:
  kubernetes.io/os: linux

# No tolerations for development
tolerations: []

# Simple affinity for development
affinity: {}
