# Custom values for azni-app deployment in azni-namspace
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.14.2"

# No command needed for pause container

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: azni-namespace-sctp-sandbox.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Add namespace-specific labels
podLabels:
  environment: production
  namespace: azni-namspace

# Add tolerations for CriticalAddonsOnly nodes
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"

# Simple probes for nginx
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Mount ConfigMap with HTML content
volumes:
  - name: html-content
    configMap:
      name: azni-app-html

volumeMounts:
  - name: html-content
    mountPath: /usr/share/nginx/html/
    readOnly: true
