apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.51.4
    helm:
      releaseName: argocd
      values: |
        server:
          extraArgs:
            - --insecure
          service:
            type: LoadBalancer
        configs:
          secret:
            argocdServerAdminPassword: "$2a$10$mzWxXxXxXxXxXxXxXxXxO" # Default password: admin
        dex:
          enabled: false
        notifications:
          enabled: true
        applicationSet:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
