{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "azni-app.fullname" . }}
  labels:
    {{- include "azni-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "azni-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from within the namespace
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
    {{- if .Values.networkPolicy.additionalIngressRules }}
    {{- toYaml .Values.networkPolicy.additionalIngressRules | nindent 4 }}
    {{- end }}
  egress:
    # Allow only specific egress if defined
    {{- if .Values.networkPolicy.egressRules }}
    {{- toYaml .Values.networkPolicy.egressRules | nindent 4 }}
    {{- else }}
    # Default egress rule allows all outbound traffic
    - {}
    {{- end }}
{{- end }} 