apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azni-app-dev
  namespace: argocd
spec:
  project: azni-project
  source:
    repoURL: https://github.com/azniosman/Assignment-3.13.git
    targetRevision: main
    path: overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
