apiVersion: apps/v1
kind: Deployment
metadata:
  name: azni-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azni-app
  template:
    metadata:
      labels:
        app: azni-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
