apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azni-app
  namespace: default
spec:
  releaseName: azni-app
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: "13.2.*"
  values:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
